# Generated by Django 5.0.4 on 2024-05-07 06:42

import django.db.models.deletion
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='news')),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('bekor pilish', 'Cancel'), ("to'g'ri", 'Success')], default=news.models.Publishchoice, max_length=40)),
                ('publish', models.CharField(choices=[('bekor pilish', 'Cancel'), ("to'g'ri", 'Success')], default='bekor pilish', max_length=30)),
                ('Categroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categroy')),
            ],
        ),
    ]
