# Generated by Django 5.0.4 on 2024-05-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Categroy',
            new_name='categroy',
        ),
        migrations.RemoveField(
            model_name='news',
            name='publish',
        ),
        migrations.AddField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='state',
            field=models.CharField(choices=[('bekor pilish', 'Cancel'), ("to'g'ri", 'Success')], default='bekor pilish', max_length=40),
        ),
    ]
