# Generated by Django 5.0.4 on 2024-06-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massege',
            new_name='message',
        ),
    ]
